apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: rohit-space
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: rohit3webapp
  name: rohit3webapp
  namespace: rohit-space #name-space is getting used
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rohit3webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rohit3webapp
    spec:
      containers:
      - image: rohitkulkarni1512/microsoftapp:v003
        name: microsoftapp
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: rohitday3s1
  name: rohitday3s1
  namespace: rohit-space # using namespace
spec:
  ports:
  - name: 5555-80
    port: 5555
    protocol: TCP
    targetPort: 80
  selector:
    app: rohit3webapp
  type: NodePort
status:
  loadBalancer: {}
